
  - name: Ansible apt install apache2
    apt:
      name: apache2
      state: present

  - name: Install software properties common
    apt: name=software-properties-common

  - name: Add PHP repo
    apt_repository: repo=ppa:ondrej/php

  - name: Update repo
    apt: update_cache=yes

  - name: apt install php
    apt:
      name: 
        - php7.2
        - php7.2-mysql
      state: present
      update_cache: true

  - name: Apache Status check
    service:
      name: apache2
      state: started

  ## Apache and PHP testing
  - name: Copy html
    copy: 
      src: '{{ item }}'
      dest: /var/www/html/
      owner: www-data
      mode: 0744
    loop:
     - files/index.html
     - files/myphpinfo.php
  
  - name: PHP Mysqli enable
    lineinfile:
      path: /etc/php/7.2/apache2/php.ini
      regexp: '^extension=mysqli'
      line: extension=mysqli
  
  - name: Reload apache2
    systemd:
      state: restarted
      daemon_reload: yes
      name: apache2

  - name: Clone a repo with separate git directory
    become: true
    git:
      repo: https://github.com/OlegShmyrin/php-mysql-crud.git
      dest: /src/
      separate_git_dir: /src/php-mysql-crud.git
    
  - name: Copy Site  
    become: true
    copy:
      src: /src/
      dest: /var/www/html/
      remote_src: yes
      owner: www-data
      mode: 0744