
  - name: Ansible apt install apache2
    apt:
      name: apache2
      state: present

  - name: Install software properties common
    apt: name=software-properties-common

  - name: Add PHP repo
    apt_repository: repo=ppa:ondrej/php

  - name: Update repo
    apt: update_cache=yes

  - name: apt install php
    apt:
      name: 
        - php7.4
        - php7.4-mysql
      state: present
      update_cache: true

  - name: Apache Status check
    service:
      name: apache2
      state: started

  ## Apache and PHP testing
  - name: Copy html
    copy: 
      src: '{{ item }}'
      dest: /var/www/html/
      owner: www-data
      mode: 0744
    loop:
     - files/index.html
     - files/myphpinfo.php
  
  - name: PHP Mysqli enable
    lineinfile:
      path: /etc/php/7.4/apache2/php.ini
      regexp: '^extension=mysqli'
      line: extension=mysqli
  
  - name: Reload apache2
    systemd:
      state: restarted
      daemon_reload: yes
      name: apache2

  # - name: Delete html dir in Apache
  #   file:
  #     path: /var/www/html/
  #     state: "absent"

  - name: Clone a repo with separate git directory
    become: true
    git:
      repo: https://github.com/OlegShmyrin/php-mysql-crud.git
      dest: /src/
      separate_git_dir: /src/php-mysql-crud.git
    
  - name: Copy Site  
    become: true
    copy:
      src: /src/
      dest: /var/www/html/
      remote_src: yes
      owner: www-data
      mode: 0744
  
  - name: Change connection string in db.php
    lineinfile:
      path: /var/www/html/db.php
      regexp: '"DB_HOST","DB_USER","DB_PASSWORD","DB_DATABASE"'
        # Line to Replace with
      line: "{{ connection_string }}"
      state: present  
    # with_items:  
    #     - {From: "DB_HOST", To: "{{ db_host }}"}
    #     - {From: "DB_USER", To:  "{{ crud_db_user }}"}
    #     - {From: DB_PASSWORD, To:  "{{ crud_db_user_password }}"}
    #     - {From: DB_DATABASE, To:  "{{ crud_db_name }}"}
     